### ISSUE TITLE
Data Set Access

### ISSUE THREAD

**Issue by dlucani** [conect2ai/Conect2Py-Package#1]
Dear all
I am testing your code and ipython notebooks.
However, the datasets listed are not provided in the repo.
Can you upload them or upload other options for easy testing of functionalities by new users?
Thanks in advance
Daniel

**Comment by MiguelEuripedes** [comment]
Greetings, @dlucani!

We've uploded a folder called [/data](https://github.com/conect2ai/Conect2Py-Package/tree/main/Data) on the main branch, there you will find the same dataset used in the notebook [TAC_UseCase_Example.ipynb](https://github.com/conect2ai/Conect2Py-Package/blob/main/TAC_UseCase_Example.ipynb).

Thanks for the contact and feedback! If you have anything else to ask, feel free to reach us! 

Miguel

**Comment by dlucani** [comment]
Dear Miguel

Many thanks - it works nicely 
Cheers

Daniel
